/*
 * extraction/ggml_verified.h
 * ─────────────────────────────────────────────────────────────────────────────
 * Public header for the KaRaMeL-extracted verified ggml kernels.
 *
 * This file is normally AUTO-GENERATED by KaRaMeL from GGML.Impl.fst.
 * It is checked in here as a reference / integration stub so that the
 * test harness and ggml.c integration shim can both #include it before
 * extraction has been run.
 *
 * Generation command (from verified-ggml/):
 *   make extract
 * which runs:
 *   krml -bundle "GGML.Types+GGML.Spec+GGML.Proofs+GGML.Impl=*" \
 *        -minimal -o ggml-verified-kernels.c                      \
 *        -tmpdir extraction/ GGML.Types.fsti GGML.Spec.fst        \
 *        GGML.Proofs.fst GGML.Impl.fst
 *
 * Naming convention produced by KaRaMeL:
 *   F* module   GGML.Impl
 *   F* val      verified_add
 *   C symbol    GGML_Impl_verified_add
 * ─────────────────────────────────────────────────────────────────────────────
 */

#ifndef GGML_VERIFIED_H
#define GGML_VERIFIED_H

#include <stdint.h>
#include <stdbool.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ── Types mirroring GGML.Types ─────────────────────────────────────────────
   KaRaMeL maps  GGML.Types_ggml_type  →  GGML_Types_ggml_type  (C enum)     */
typedef enum {
  GGML_Types_F32  = 0,
  GGML_Types_F16  = 1,
  GGML_Types_Q4_0 = 2,
  GGML_Types_Q8_0 = 3,
} GGML_Types_ggml_type;

/* ── verified_add ────────────────────────────────────────────────────────────
 * Element-wise F32 addition for contiguous tensors.
 *
 * Formally proved:
 *   ∀ i < n_elems:  dst[i] = src0[i] + src1[i]
 *   No read or write outside [0, n_elems * 4) bytes for any buffer.
 *
 * Parameters:
 *   dst, src0, src1  – pointers to byte buffers of at least n_elems*4 bytes
 *   n_elems          – element count (not byte count)
 *
 * Preconditions (caller's responsibility, match F* requires clause):
 *   - All three buffers are live and non-NULL
 *   - dst is disjoint from src0 and src1
 *   - n_elems * 4 ≤ buffer capacity for all three buffers
 */
void GGML_Impl_verified_add(
    uint8_t       *dst,
    const uint8_t *src0,
    const uint8_t *src1,
    uint64_t       n_elems);

/* ── verified_scale ──────────────────────────────────────────────────────────
 * Element-wise scalar multiply: dst[i] = src[i] * scalar
 *
 * Formally proved: same memory-safety guarantees as verified_add.
 */
void GGML_Impl_verified_scale(
    uint8_t       *dst,
    const uint8_t *src,
    float          scalar,
    uint64_t       n_elems);

/* ── verified_relu ───────────────────────────────────────────────────────────
 * Element-wise ReLU: dst[i] = max(0.0f, src[i])
 *
 * Formally proved: same memory-safety guarantees as verified_add.
 */
void GGML_Impl_verified_relu(
    uint8_t       *dst,
    const uint8_t *src,
    uint64_t       n_elems);

/* ── verified_contiguous_check ───────────────────────────────────────────────
 * Pure (no side effects) contiguous-layout validator.
 * Mirrors ggml_is_contiguous() from ggml.c (lines 56673-56698).
 *
 * Returns true iff the stride array (nb) encodes a fully contiguous layout
 * for a tensor of the given type and element counts.
 *
 * Formally proved TOTAL: always terminates, no undefined behaviour.
 */
bool GGML_Impl_verified_contiguous_check(
    GGML_Types_ggml_type ty,
    uint64_t ne0, uint64_t ne1, uint64_t ne2, uint64_t ne3,
    uint64_t nb0, uint64_t nb1, uint64_t nb2, uint64_t nb3);

#ifdef __cplusplus
}
#endif
#endif /* GGML_VERIFIED_H */
